### ISSUE TITLE
Add YAML linter

### ISSUE THREAD

**Issue by yolocs** [abcxyz/pkg#130]
### TL;DR

To check all YAML strings are quoted as well as license header

**Comment by sethvargo** [comment]
I wonder if I can nerdsnipe @drevell into doing this...

**Comment by drevell** [comment]
Sure, I'll do this in a couple of weeks. If someone else wants to do it before then, that would be fine with e.

**Comment by pdewilde** [comment]
Be careful what you agree to, string quotes are just the tip of the YAML iceberg :)

**Comment by sethvargo** [comment]
Turns out yamllint is just installed on the GHA runners...
