### ISSUE TITLE
[go-lint] Disable checks for direct usage of loop variables

### ISSUE THREAD

**Issue by sqin2019** [abcxyz/pkg#313]
This issue disappears with Go 1.22 because the loop variable is not reused, ref https://tip.golang.org/doc/go1.22
linters related: gosec G601, govet, exportloopref.

**Comment by sethvargo** [comment]
Looks like _paralleltest_ also doesn't support this config option yet. For now, let's keep adding it.

**Comment by yolocs** [comment]
Filed an issue: https://github.com/golangci/golangci-lint/issues/4511

**Comment by sethvargo** [comment]
This seems like it was fixed upstream
